7098585 pkg support for upgrading to fcs release needed
--HG--
branch : 2010.2H

diff --git a/src/brand/attach b/src/brand/attach
--- a/src/brand/attach
+++ b/src/brand/attach
@@ -21,15 +21,16 @@
 #
 
 #
-# Copyright (c) 2010, 2011, Oracle and/or its affiliates. All rights reserved.
+# Copyright (c) 2008, 2011, Oracle and/or its affiliates. All rights reserved.
 #
 
 . /usr/lib/brand/ipkg/common.ksh
 
 m_attach_log=$(gettext "Log File: %s")
 m_zfs=$(gettext "A ZFS file system was created for the zone.")
-m_attaching=$(gettext "Attaching...")
 m_usage=$(gettext  "attach [-a archive] [-d dataset] [-n] [-r zfs-recv] [-u]\n\tThe -a archive option specifies a tar file or cpio archive.\n\tThe -d dataset option specifies an existing dataset.\n\tThe -r zfs-recv option receives the output of a 'zfs send' command\n\tof an existing zone root dataset.\n\tThe -u option indicates that the software should be updated to match\n\tthe current host.")
+m_attach_root=$(gettext "               Attach Path: %s")
+m_attach_ds=$(gettext   "        Attach ZFS Dataset: %s")
 m_gzinc=$(gettext       "       Global zone version: %s")
 m_zinc=$(gettext        "   Non-Global zone version: %s")
 m_need_update=$(gettext "                Evaluation: Packages in zone %s are out of sync with the global zone. To proceed, retry with the -u flag.")
@@ -38,11 +39,22 @@ m_updating=$(gettext    "  Updating non-global zone: Output follows")
 m_sync_done=$(gettext   "  Updating non-global zone: Zone updated.")
 m_complete=$(gettext    "                    Result: Attach Succeeded.")
 m_failed=$(gettext      "                    Result: Attach Failed.")
-sanity_fail_global=$(gettext  "  Sanity Check: FAILED, the image is from the global zone.")
+
+#
+# These two messages are used by the install_image function in
+# /usr/lib/brand/shared/common.ksh.  Yes, this is terrible.
+#
+installing=$(gettext    "                Installing: This may take several minutes...")
+no_installing=$(gettext "                Installing: Using pre-existing data in zonepath")
+
+f_sanity_variant=$(gettext "  Sanity Check: FAILED, couldn't determine %s from image.")
+f_sanity_global=$(gettext  "  Sanity Check: FAILED, appears to be a global zone (%s=%s).")
 f_update=$(gettext "Could not update attaching zone")
 f_no_pref_publisher=$(gettext "Unable to get preferred publisher information for zone '%s'.")
 f_nosuch_key=$(gettext "Failed to find key %s for global zone publisher")
 f_nosuch_cert=$(gettext "Failed to find cert %s for global zone publisher")
+f_ds_config=$(gettext  "Failed to configure dataset %s: could not set %s.")
+f_no_active_ds_mounted=$(gettext  "Failed to locate any dataset mounted at %s.  Attach requires a mounted dataset.")
 
 # Clean up on interrupt
 trap_cleanup() {
@@ -70,10 +82,15 @@ trap_exit() {
 			# Restore the zone properties for the pre-existing
 			# dataset.
 			if [[ -n "$ACTIVE_DS" ]]; then
-				zfs set zoned=off $ACTIVE_DS >/dev/null 2>&1
-				zfs set canmount=on $ACTIVE_DS >/dev/null 2>&1
-				zfs set mountpoint=$ZONEROOT $ACTIVE_DS \
-				    >/dev/null 2>&1
+				zfs set zoned=off $ACTIVE_DS
+				(( $? != 0 )) && error "$f_ds_config" \
+				    "$ACTIVE_DS" "zoned=off"
+				zfs set canmount=on $ACTIVE_DS
+				(( $? != 0 )) && error "$f_ds_config" \
+				    "$ACTIVE_DS" "canmount=on"
+				zfs set mountpoint=$ZONEROOT $ACTIVE_DS
+				(( $? != 0 )) && error "$f_ds_config" \
+				    "$ACTIVE_DS" "mountpoint=$ZONEROOT"
 			fi
 		fi
 		log "$m_failed"
@@ -160,7 +177,11 @@ gather_zone_publisher_details() {
 		if [[ -z $origin ]]; then
 			origin=$name
 			name=${publisher.name}
+		elif [[ "$origin" == "None" ]]; then
+			# Publisher with no origins.
+			origin=""
 		fi
+
 		# Use a compound variable to store all the data
 		# relating to a publisher.
 		if [[ -z ${publishers[$name]} ]]; then
@@ -178,14 +199,22 @@ gather_zone_publisher_details() {
 			get_publisher_attrs ${publisher.name} origin | \
 			    IFS=" " read publisher.sticky publisher.preferred \
 			    publisher.enabled
-			get_pub_secinfo ${publisher.name} | \
-			    read publisher.keyfile publisher.certfile
-			[[ ${publisher.keyfile} != "None" && \
-			    ! -f ${PKG_IMAGE}/${publisher.keyfile} ]] && \
-			    fail_usage "$f_nosuch_key" ${publisher.keyfile}
-			[[ ${publisher.certfile} != "None" && \
-			    ! -f ${PKG_IMAGE}/${publisher.certfile} ]] && \
-			    fail_usage "$f_nosuch_cert" ${publisher.certfile}
+			if [[ -n "$origin" ]]; then
+				get_pub_secinfo ${publisher.name} | \
+				    read publisher.keyfile publisher.certfile
+				[[ ${publisher.keyfile} != "None" && \
+				    ! -f ${PKG_IMAGE}/${publisher.keyfile} ]] && \
+				    fail_usage "$f_nosuch_key" \
+				        ${publisher.keyfile}
+				[[ ${publisher.certfile} != "None" && \
+				    ! -f ${PKG_IMAGE}/${publisher.certfile} ]] && \
+				    fail_usage "$f_nosuch_cert" \
+				        ${publisher.certfile}
+			else
+				# Publisher has no origins.
+				publisher.keyfile="None"
+				publisher.certfile="None"
+			fi
 			publisher_count=publisher_count+1
 			url_count=0
 		fi
@@ -378,15 +407,22 @@ if [[ "$install_media" == "-" ]]; then
 		    print $1
 	}'`
 
-	[[ -z "$ACTIVE_DS" ]] && fatal "$f_no_active_ds"
+	[[ -z "$ACTIVE_DS" ]] && fatal "$f_no_active_ds_mounted" $ZONEROOT
 
 	# Set up proper attributes on the ROOT dataset.
 	get_zonepath_ds $ZONEPATH
 	zfs list -H -t filesystem -o name $ZONEPATH_DS/ROOT >/dev/null 2>&1
 	(( $? != 0 )) && fatal "$f_no_active_ds"
 
-	zfs set mountpoint=legacy $ZONEPATH_DS/ROOT >/dev/null 2>&1
-	zfs set zoned=on $ZONEPATH_DS/ROOT >/dev/null 2>&1
+	# need to ensure zoned is off to set mountpoint=legacy.
+	zfs set zoned=off $ZONEPATH_DS/ROOT
+	(( $? != 0 )) && fatal "$f_ds_config" $ZONEPATH_DS/ROOT "zoned=off"
+
+	zfs set mountpoint=legacy $ZONEPATH_DS/ROOT
+	(( $? != 0 )) && fatal "$f_ds_config" $ZONEPATH_DS/ROOT \
+	    "mountpoint=legacy"
+	zfs set zoned=on $ZONEPATH_DS/ROOT
+	(( $? != 0 )) && fatal "$f_ds_config" $ZONEPATH_DS/ROOT "zoned=on"
 
 	#
 	# We're typically using a pre-existing mounted dataset so setting the
@@ -397,11 +433,19 @@ if [[ "$install_media" == "-" ]]; then
 	# and attempt the remount if necessary.
 	#
 	get_current_gzbe
-	zfs set $PROP_PARENT=$CURRENT_GZBE $ACTIVE_DS >/dev/null 2>&1
-	zfs set $PROP_ACTIVE=on $ACTIVE_DS >/dev/null 2>&1
-	zfs set canmount=noauto $ACTIVE_DS >/dev/null 2>&1
-	zfs inherit mountpoint $ACTIVE_DS >/dev/null 2>&1
-	zfs inherit zoned $ACTIVE_DS >/dev/null 2>&1
+	zfs set $PROP_PARENT=$CURRENT_GZBE $ACTIVE_DS
+	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS \
+	    "$PROP_PARENT=$CURRENT_GZBE"
+	zfs set $PROP_ACTIVE=on $ACTIVE_DS
+	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "$PROP_ACTIVE=on"
+	zfs set canmount=noauto $ACTIVE_DS
+	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "canmount=noauto"
+	zfs set zoned=off $ACTIVE_DS
+	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "zoned=off"
+	zfs inherit mountpoint $ACTIVE_DS
+	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "'inherit mountpoint'"
+	zfs inherit zoned $ACTIVE_DS
+	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "'inherit zoned'"
 
 	mounted_ds=`mount -p | nawk -v zroot=$ZONEROOT '{
 	    if ($3 == zroot && $4 == "zfs")
@@ -436,7 +480,10 @@ fi
 # The zone's datasets are now in place.
 #
 
-log "$m_attaching"
+log "$m_attach_root" "$ZONEROOT"
+# note \n to add whitespace
+log "$m_attach_ds\n" "$ACTIVE_DS"
+
 install_image "$inst_type" "$install_media"
 
 #
@@ -444,15 +491,20 @@ install_image "$inst_type" "$install_media"
 #
 
 #
-# Perform a final sanity check to confirm the image is not of the global zone.
-# Check for a few well-known global zone only svcs.
+# Perform a sanity check to confirm that the image is not a global zone.
 #
-[[ -f $ZONEROOT/var/svc/manifest/system/sysevent.xml ]] && \
-    fatal "$sanity_fail_global"
-[[ -f $ZONEROOT/var/svc/manifest/system/zones.xml ]] && \
-    fatal "$sanity_fail_global"
-[[ -f $ZONEROOT/var/svc/manifest/system/dumpadm.xml ]] && \
-    fatal "$sanity_fail_global"
+VARIANT=variant.opensolaris.zone
+variant=$(LC_ALL=C $PKG -R $ZONEROOT variant -H $VARIANT)
+[[ $? -ne 0 ]] && fatal "$f_sanity_variant" $VARIANT
+
+echo $variant | IFS=" " read variantname variantval
+[[ $? -ne 0 ]] && fatal "$f_sanity_variant"
+
+# Check that we got the output we expect...
+[[ $variantname = "$VARIANT" ]] || fatal "$f_sanity_variant" $VARIANT
+
+# Check that the variant is non-global, else fail
+[[ $variantval = "nonglobal" ]] || fatal "$f_sanity_global" $VARIANT $variantval
 
 # We would like to ensure that our NGZ publishers are a superset of
 # those in the GZ. We do this by building a list of all publishers in
@@ -475,7 +527,7 @@ if [[ $? -ne 0 ]]; then
 	fail_usage "$f_no_pref_publisher" "global"
 fi
 
-log "preferred global publisher: $gz_publisher_pref"
+vlog "Preferred global publisher: $gz_publisher_pref"
 
 #
 # Try to find the "entire" incorporation's FMRI in the gz.
@@ -502,7 +554,7 @@ PKG_IMAGE="$ZONEROOT"
 ngz_entire_fmri=$(get_entire_incorp)
 
 [[ -n $gz_entire_fmri ]] && log "$m_gzinc" "$gz_entire_fmri"
-[[ -n $ngz_entire_fmri ]] && log "$m_zinc\n" "$ngz_entire_fmri"
+[[ -n $ngz_entire_fmri ]] && log "$m_zinc" "$ngz_entire_fmri"
 
 #
 # Create the list of incorporations we wish to install/update in the
@@ -518,10 +570,10 @@ fi
 #
 # If there is a cache, use it.
 #
-if [ -d /var/pkg/download ]; then
-	PKG_CACHEDIR=/var/pkg/download
-	export PKG_CACHEDIR
-	log "$m_cache" "$PKG_CACHEDIR"
+if [[ -f /var/pkg/pkg5.image && -d /var/pkg/publisher ]]; then
+	PKG_CACHEROOT=/var/pkg/publisher
+	export PKG_CACHEROOT
+	log "$m_cache" "$PKG_CACHEROOT"
 fi
 
 log "$m_updating"
@@ -595,7 +647,7 @@ if [[ -z $gz_entire_fmri && -n $ngz_entire_fmri ]]; then
 	if [[ $allow_update == 1 ]]; then
 		LC_ALL=C $PKG uninstall entire || pkg_err_check "$f_update"
 	else
-		log "$m_need_update" "$ZONENAME"
+		log "\n$m_need_update" "$ZONENAME"
 		EXIT_CODE=$ZONE_SUBPROC_NOTCOMPLETE
 		exit $EXIT_CODE
     fi
@@ -604,11 +656,11 @@ fi
 if [[ $allow_update == 0 ]]; then
 	LC_ALL=C $PKG install --accept --no-refresh -n $incorp_list
 	if [[ $? == 4 ]]; then
-		log "$m_complete"
+		log "\n$m_complete"
 		EXIT_CODE=$ZONE_SUBPROC_OK
 		exit $EXIT_CODE
 	else
-		log "$m_need_update" "$ZONENAME"
+		log "\n$m_need_update" "$ZONENAME"
 		EXIT_CODE=$ZONE_SUBPROC_NOTCOMPLETE
 		exit $EXIT_CODE
 	fi
@@ -628,7 +680,7 @@ fi
 LC_ALL=C $PKG install --accept --no-refresh $incorp_list  || \
     pkg_err_check "$f_update"
 
-log "$m_sync_done"
+log "\n$m_sync_done"
 log "$m_complete"
 
 EXIT_CODE=$ZONE_SUBPROC_OK
diff --git a/src/pkg/Makefile b/src/pkg/Makefile
--- a/src/pkg/Makefile
+++ b/src/pkg/Makefile
@@ -18,14 +18,22 @@
 #
 # CDDL HEADER END
 #
-# Copyright (c) 2010, Oracle and/or its affiliates. All rights reserved.
+# Copyright (c) 2010, 2011, Oracle and/or its affiliates. All rights reserved.
 #
 
 PKGVERS_COMPONENT = 0.5.11
 PKGVERS_BUILTON   = 5.11
-BUILDNUM.cmd      = hg tags | nawk '$$1 ~ /^in[0-9]*$$/ {print substr($$1, 3) + 1; exit}'
-BUILDNUM          = $(BUILDNUM.cmd:sh)
-CURBUILD.cmd      = pkg -R / list -H osnet-incorporation | sed -e 's/.*-0\.\([^ ]*\).*/\1/'
+BUILDNUM          = 151
+UPDATENUM         = 0
+SRUNUM            = 0
+PLATNUM           = 0
+BUILDID           = 0
+NIGHTLYID:sh      = hg parents --template '{rev}'
+CHANGESET.cmd     = hg id -i
+CHANGESET         = $(CHANGESET.cmd:sh)
+CURBUILD.cmd      = \
+	$(PKG) -R / list -H osnet-incorporation | \
+		sed -e 's/.*-0\.\([^ .]*\).*/\1/'
 CURBUILD          = $(CURBUILD.cmd:sh)
 PKGVERS_BRANCH    = 0.$(BUILDNUM)
 PKGVERS           = $(PKGVERS_COMPONENT),$(PKGVERS_BUILTON)-$(PKGVERS_BRANCH)
@@ -37,8 +45,7 @@ REV               = $(REV.cmd:sh)
 PDIR              = pkgtmp
 PWD:sh            = pwd
 PKGDEST           = $(PWD)/../../packages/$(ARCH)
-PKGROOT           = ../../proto/root_$(ARCH)
-PKGLINT           = $(PKGROOT)/usr/bin/pkglint -f $(PKGROOT)/usr/share/lib/pkg/pkglintrc
+PKGROOT           = $(PWD)/../../proto/root_$(ARCH)
 
 PKGPUBLISHER      = pkg5-nightly
 
@@ -49,20 +56,36 @@ MANIFESTS.cmd     = \
 	buildnum=$(BUILDNUM); \
 	m=$$($(PKGMOGRIFY) -O /dev/null *.p5m ../transforms/nopublish); \
 	echo "$$m" | while read name build; do \
-		[[ $$build -gt $${buildnum%%.*} ]] && echo $$name; \
-	done
+		[[ $$build -ge $${buildnum%%.*} ]] && echo $$name; \
+	done | sed -e 's/:/\\:/g' ; exit 0
 MANIFESTS         = $(MANIFESTS.cmd:sh)
-$(PUBLISHALL)MANIFESTS:sh      = (cd manifests; print *.p5m)
-PKGS.cmd          = print $(MANIFESTS:%.p5m=%) | sed -e s/%2F/\\//g
-PKGS              = $(PKGS.cmd:sh)
-PKGMOGRIFY        = pkgmogrify
-PKGSEND           = pkgsend
-PKGREPO           = pkgrepo
+$(PUBLISHALL)MANIFESTS:sh      = \
+	(cd manifests; print *.p5m | sed -e 's/:/\\:/g')
+PKGCMDENV         = \
+	PATH=$(PKGROOT)/usr/bin:/usr/sbin:/usr/bin \
+		PYTHONPATH=$(PKGROOT)/usr/lib/python2.6/vendor-packages
+PKG               = $(PKGCMDENV) pkg
+PKGDEPEND         = $(PKGCMDENV) pkgdepend
+PKGLINT           = $(PKGCMDENV) pkglint
+PKGMOGRIFY        = $(PKGCMDENV) pkgmogrify
+PKGREPO           = $(PKGCMDENV) pkgrepo
+PKGSEND           = $(PKGCMDENV) pkgsend
 MOGRIFESTS        = $(MANIFESTS:%.p5m=$(PDIR)/%.mog)
 PUBLIFESTS        = $(MANIFESTS:%.p5m=$(PDIR)/%.pub)
-INCORP            = consolidation%2Fips%2Fips-incorporation
+DEPENDED          = $(MANIFESTS:%.p5m=$(PDIR)/%.dep)
+INCORP            = consolidation\:ips\:ips-incorporation
 
 PM_TRANSFORMS     = defaults
+
+i386_DEFINES=       \
+	i386_ONLY=''    \
+	sparc_ONLY=$(POUND_SIGN)
+
+sparc_DEFINES=      \
+	i386_ONLY=$(POUND_SIGN) \
+	sparc_ONLY=''
+
+ARCH_DEFINES=$($(ARCH)_DEFINES)
 
 PKGMOG_DEFVALS    = \
 	ARCH=$(ARCH) \
@@ -73,8 +96,10 @@ PKGMOG_DEFVALS    = \
 	REV=$(REV) \
 	CURBUILD_BRANCH=0.$(CURBUILD) \
 	PYDIR=usr/lib/python2.6 \
-	PYDIRVP=usr/lib/python2.6/vendor-packages
+	PYDIRVP=usr/lib/python2.6/vendor-packages \
+	CHANGESET=$(CHANGESET)
 PKGMOG_DEFINES    = $(PKGMOG_DEFVALS:%=-D %)
+PKGMOG_DEFINES    += $(ARCH_DEFINES:%=-D %)
 
 all: $(MOGRIFESTS)
 install: lint
@@ -88,6 +113,11 @@ clobber: clean
 # Pass SVr4 package production off to its own makefile
 svr4:
 	$(MAKE) -f Makefile.svr4 _svr4
+
+# A target used to only build the SVR4 packages needed for
+# the test suite
+svr4_test:
+	$(MAKE) -f Makefile.svr4 _svr4_test
 
 $(PDIR):
 	mkdir -p $@
@@ -107,19 +137,33 @@ $(PKGDEST)/repo:
 # looks at all manifests, not just the ones listed in $(MANIFESTS).  This is
 # because we need to incorporate obsolete and renamed packages, even if we
 # choose not to continue republishing them.
-$(PDIR)/$(INCORP).mog: manifests/$(INCORP).p5m $(PDIR) transforms/incorp
-	$(PKGMOGRIFY) -I transforms incorp2 manifests/$(INCORP).p5m | \
+$(PDIR)/$(INCORP).mog: manifests/$(INCORP).p5m $(PDIR) \
+	$(MOGRIFESTS:$(PDIR)/$(INCORP).mog=)
+	$(PKGMOGRIFY) -I transforms defaults incorp2 manifests/$(INCORP).p5m | \
 		$(PKGMOGRIFY) $(PKGMOG_DEFINES) -D DEPTYPE=incorporate \
-		-I transforms -O $@ /dev/stdin incorp manifests/*.p5m
+		-I transforms -O $@ /dev/stdin incorp \
+		$(MOGRIFESTS:$(PDIR)/$(INCORP).mog=)
 
 # The main mogrification rule
-$(PDIR)/%.mog: manifests/%.p5m $(PM_TRANSFORMS:%=transforms/%) $(PDIR) $(PM_TRANSFORMS:%=transforms/%)
+$(PDIR)/%.mog: manifests/%.p5m $(PM_TRANSFORMS:%=transforms/%) $(PDIR) \
+	$(PM_TRANSFORMS:%=transforms/%)
 	$(PKGMOGRIFY) $(PKGMOG_DEFINES) -I transforms -O $@ $< $(PM_TRANSFORMS)
 
+# The main dependency generation rule
+$(PDIR)/%.dep: $(PDIR)/%.mog
+	$(PKGDEPEND) generate -m -d $(PKGROOT) $< > $@
+
+# Resolve all dependencies at once, providing a single target that publication
+# can use.
+$(PDIR)/.resolved: $(DEPENDED)
+	$(PKGDEPEND) resolve -m $(DEPENDED)
+	touch $@
+
 # The main publication rule
-$(PDIR)/%.pub: $(PDIR)/%.mog $(PKGDEST)/repo
-	$(PKGSEND) -s file://$(PKGDEST)/repo publish -d $(PKGROOT) -d license_files \
-		-T \*.py --fmri-in-manifest --no-index --no-catalog $<
+$(PDIR)/%.pub: $(PDIR)/.resolved $(PKGDEST)/repo
+	$(PKGSEND) -s file://$(PKGDEST)/repo publish -d $(PKGROOT) \
+		-d license_files -T \*.py --fmri-in-manifest --no-index \
+		--no-catalog $(@:%.pub=%.dep.res)
 	touch $@
 
 # Compare the proto area with the package manifests; if they've got different
@@ -142,46 +186,56 @@ check: $(PDIR)/protomanifest $(PDIR)/pkgmanifest
 #
 # If new warnings/errors appear in the lint output, we return an error.
 #
+# To tell pkglint to bypass any potential missing dependencies during
+# the lint run, please edit external_deps.pkglintrc
 lint: repository-metadata
-	# Ensure that the shipped pkglint_whitelist.txt is self-consistent.
-	# That is, when sorting it in the C locale and diffing the output
-	# against itself, we should see no differences.
-	# (This catches whitelist putbacks that aren't correctly sorted)
-	env LC_ALL=C sort pkglint_whitelist.txt | diff - pkglint_whitelist.txt
+	@sed -e "s#/usr/share/lib/pkg/opensolaris.org.sections#$(PKGROOT)&#" \
+		< ips-pkglintrc > $(PDIR)/pkglintrc
+
+	@# Ensure that the shipped pkglint_whitelist.txt is self-consistent.
+	@# That is, when sorting it in the C locale and diffing the output
+	@# against itself, we should see no differences.
+	@# (This catches whitelist putbacks that aren't correctly sorted)
+	@env LC_ALL=C sort pkglint_whitelist.txt | diff - pkglint_whitelist.txt
 	@echo "Running pkglint"
 	@rm -rf $(PDIR)/pkglint-cache
 	@rm -f $(PDIR)/pkglint-out*
 	@if [ -n "$(PKGLINT_REF_REPO)" ]; then				\
-		$(PKGLINT) -c $(PDIR)/pkglint-cache 			\
+		env LC_ALL=C $(PKGLINT) -f $(PDIR)/pkglintrc \
+			-c $(PDIR)/pkglint-cache \
 			-r $(PKGLINT_REF_REPO) -l file://$(PKGDEST)/repo; \
 	fi
-	-@if [ -z "$(PKGLINT_REF_REPO)" ]; then 			\
-		( $(PKGLINT) -c $(PDIR)/pkglint-cache 			\
+	-@if [ -z "$(PKGLINT_REF_REPO)" ]; then				\
+		cat external_deps.pkglintrc >> $(PDIR)/pkglintrc;	\
+		( $(PKGLINT) -c $(PDIR)/pkglint-cache			\
+			-f $(PDIR)/pkglintrc				\
 			-l file://$(PKGDEST)/repo > /dev/null ) 2>&1 |	\
 			sed -e 's/@[0-9TZ.:,-]*//g' |			\
 			env LC_ALL=C sort |				\
 			diff pkglint_whitelist.txt -			\
-			> $(PDIR)/pkglint-out-diff.txt; 		\
+			| grep -v pkglint.manifest007			\
+			| grep -v pkglint.action008			\
+			> $(PDIR)/pkglint-out-diff.txt;			\
 									\
-		egrep "^< WARNING |^< ERROR |^< CRITICAL " 		\
-			$(PDIR)/pkglint-out-diff.txt 			\
-			> $(PDIR)/pkglint-out-fixes.txt; 		\
- 		egrep -v "^< WARNING |^< ERROR |^< CRITICAL "		\
-			$(PDIR)/pkglint-out-diff.txt 			\
-			| sed -e '/^[0-9,]*[ad][0-9,]*$$/d' 		\
-			> $(PDIR)/pkglint-out-breakage.txt; 		\
+		egrep "^< WARNING |^< ERROR |^< CRITICAL "		\
+			$(PDIR)/pkglint-out-diff.txt			\
+			> $(PDIR)/pkglint-out-fixes.txt;		\
+		egrep -v "^< WARNING |^< ERROR |^< CRITICAL "		\
+			$(PDIR)/pkglint-out-diff.txt			\
+			| sed -e '/^[0-9,]*[ad][0-9,]*$$/d'		\
+			> $(PDIR)/pkglint-out-breakage.txt;		\
 	fi
-	@if [ -s $(PDIR)/pkglint-out-fixes.txt ]; then 			\
+	@if [ -s $(PDIR)/pkglint-out-fixes.txt ]; then			\
 		echo "";						\
-		echo "The following pkglint errors are now fixed:"; 	\
-		cat $(PDIR)/pkglint-out-fixes.txt; 			\
+		echo "The following pkglint errors are now fixed:";	\
+		cat $(PDIR)/pkglint-out-fixes.txt;			\
 		echo "pkglint-whitelist.txt should be updated";		\
 	fi
-	@if [ -s $(PDIR)/pkglint-out-breakage.txt ]; then 		\
+	@if [ -s $(PDIR)/pkglint-out-breakage.txt ]; then		\
 		echo "";						\
 		echo "New pkglint errors detected:";			\
-		cat $(PDIR)/pkglint-out-breakage.txt; 			\
-		exit 1; 						\
+		cat $(PDIR)/pkglint-out-breakage.txt;			\
+		exit 1;						\
 	fi
 
 # A little bit of Python is the easiest way to generate the commandline options
@@ -198,6 +252,7 @@ $(PDIR)/protomanifest: FRC transforms/compare-strip $(PDIR)
 
 # Create a pseudo-manifest of the combined packages
 $(PDIR)/pkgmanifest: $(MOGRIFESTS) transforms/compare-strip $(PDIR)
-	$(PKGMOGRIFY) $(PKGMOG_DEFINES) transforms/compare-strip $(MOGRIFESTS) > $@
+	$(PKGMOGRIFY) $(PKGMOG_DEFINES) transforms/compare-strip $(MOGRIFESTS) \
+		> $@
 
 FRC:
